#!/bin/bash -ex

interface=test-client
destination=server.example.net

ip -4 address flush scope global
ip -6 address flush scope global

dhcpcd -k $interface || true
dhcpcd $interface --debug --script ./script

ping -q -c1 $destination

dhcpcd -k $interface
