#!/bin/bash -ex

ip -4 address flush scope global
ip -6 address flush scope global

dhcpcd -k $INTERFACE || true
dhcpcd $INTERFACE --debug --script ./script

ping -q -c1 $DESTINATION

dhcpcd -k $INTERFACE
