#!/usr/bin/python3

import os, asyncio

servname = os.environ['DEFAULT_SERVICE']

class Protocol(asyncio.Protocol):
    def connection_made(self, transport):
        self.transport = transport

    def data_received(self, data):
        self.transport.write(data)

loop = asyncio.get_event_loop()
server = loop.run_until_complete(loop.create_server(Protocol, None, servname))
loop.run_until_complete(server.wait_closed())
