#!/usr/bin/python

from __future__ import print_function

import os, sys, socket

nodename = os.environ['DESTINATION']
servname = os.environ['DEFAULT_SERVICE']
family = socket.AF_UNSPEC
socktype = socket.SOCK_STREAM
protocol = socket.IPPROTO_TCP

for ai in socket.getaddrinfo(nodename, servname, family, socktype, protocol):
    family, socktype, protocol, canonname, sa = ai

    try:
        sock = socket.socket(family, socktype, protocol)
        sock.connect(sa)
        sock.send("TEST")
        print(sock.recv(4096))
        sock.shutdown(socket.SHUT_RDWR)
        sock.close()
        exit(0)
    except socket.error as error:
        print(error, file=sys.stderr)

exit(1)
