#!/usr/bin/python

from __future__ import print_function

import os, sys, socket

for family in socket.AF_INET6, socket.AF_INET:
    sock = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
    try:
        sock.connect((os.environ['DESTINATION'], 80))
        sock.send("TEST")
        data = sock.recv(4096)
        print(data)
        sock.shutdown(socket.SHUT_RDWR)
        sock.close()
        exit(0)
    except socket.error as error:
        print(error, file=sys.stderr)
