#!/usr/bin/python

import os, socket, select

sockets = []

for family in socket.AF_INET, socket.AF_INET6:
    if family == socket.AF_INET:
        continue
    sock = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
    sock.bind(("0.0.0.0" if family == socket.AF_INET else "::", int(os.environ.get('DEFAULT_PORT', '80'))))
    sock.listen(socket.SOMAXCONN)
    sockets.append(sock)

r, w, x = select.select(sockets, [], [], 10)

for listener in r:
    sock, address = listener.accept()
    data = sock.recv(4096)
    sock.send(data)
