#!/usr/bin/python

import os, socket, select

sockets = []

for family in socket.AF_INET, socket.AF_INET6:
    sock = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
    if family == socket.AF_INET6:
        sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
    sock.bind(("0.0.0.0" if family == socket.AF_INET else "::", 80))
    sock.listen(socket.SOMAXCONN)
    sockets.append(sock)

r, w, x = select.select(sockets, [], [], 10)

for listener in r:
    sock, address = listener.accept()
    data = sock.recv(4096)
    sock.send(data)
