#!/bin/bash -e
mkdir -p /run/fedora-networking/raddb
cd /run/fedora-networking
cp -R /etc/raddb/* raddb/
chmod -R 755 raddb

DESTINATION="${DESTINATION:-localhost}"

cat <<EOF >> /etc/raddb/users
testUser    Cleartext-Password := "hello"
            Reply-Message := "Hello, %{User-Name}"
EOF

sed -i "s/ipaddr\s*= .*/ipaddr = */" raddb/clients.conf

sed -i "s/ipaddr\s*= .*/ipaddr = $DESTINATION/" raddb/sites-enabled/default

exec `which radiusd` -X -d /run/fedora-networking/raddb
