#!/bin/bash -e

mkdir -p /run/fedora-networking
cd /run/fedora-networking

[ -f id_rsa -a -f id_rsa.pub ] || ssh-keygen -f id_rsa -P ''

exec  `which sshd` -D -e -o "AuthorizedKeysFile /run/fedora-networking/id_rsa.pub"
