#!/usr/bin/python3

from __future__ import print_function

import os, asyncio

nodename = os.environ['DESTINATION']
servname = os.environ['DEFAULT_SERVICE']

loop = asyncio.get_event_loop()
reader, writer = loop.run_until_complete(asyncio.open_connection(nodename, servname))
writer.write(b"TEST\n")
print(loop.run_until_complete(reader.readline()).decode('ascii').strip())
